### ISSUE TITLE
The AcfNet test results on KITTI2015 

### ISSUE THREAD

**Issue by ziming-liu** [DeepMotionAIResearch/DenseMatchingBenchmark#21]
Helllo, I have tried to reproduce the results of Acfnet in the paper. 
1- I use the scene-flow epoch20-long pretrained parameters for initialization.
2- I train the acfnet-uniform for 600epoch on 2 GTX 2080Ti with 2X2batch size, train the acfnet-adaptive for 275 epoches on 2 GXT2080Ti with 2X1 batch size (lilimited by the GPUmemory)

But the test results from official website are much poor than the results in the paper. I directly use the given config for kitti2015 in this repo. 

What problem maybe cause this??? anyone can give an idea?

acfnet-uniform result:

Error | D1-bg | D1-fg | D1-all
-- | -- | -- | --
All / All | 1.96 | 4.92 | 2.45
All / Est | 1.96 | 4.92 | 2.45
Noc / All | 1.78 | 4.59 | 2.24
Noc / Est | 1.78 | 4.59 | 2.24

acfnet-adaptive result:

Error | D1-bg | D1-fg | D1-all
-- | -- | -- | --
All / All | 2.04 | 4.08 | 2.38
All / Est | 2.04 | 4.08 | 2.38
Noc / All | 1.87 | 3.79 | 2.18
Noc / Est | 1.87 | 3.79 | 2.18

the result in the paper:

ALL-D1-ALL 1.89
NOC-D1-ALL 1.72

**Comment by youmi-zym** [comment]
Hi, @ziming-liu 
1st, make sure you pull the latest code as we fixed a bug about 2 months ago.
2nd, make sure you use the same config and training schedule as we do because KITTI is kind of hard to get a good result. As you only have 2 GPUS, you can try our published config first and then try the same iterations as our training schedule.
3rd, you can try our released ['LocalSoftArgmin'](https://github.com/DeepMotionAIResearch/DenseMatchingBenchmark/blob/master/configs/AcfNet/ResultOfAcfNet.md#how-to) code, as we found it gives a more stable result and sometimes maybe better.

Please tell me the result you have tried, and give more details, such as tensorboard and conf, disp map for analysing your problems.
