### ISSUE TITLE
question about the occlusion metrics

### ISSUE THREAD

**Issue by chenglong0313** [DeepMotionAIResearch/DenseMatchingBenchmark#9]
When I evaluate my model using your occlusion and not-occlusion metric, something goes strange.

EPE of some model on kitti validation set is follow: 
all_epe : 0.81
noc_epe: 0.61
occ_epe: 0.83

it seems that my epe is dominated by occ area. 
Then I find in your occlusion judgment code， occ points is much more than noc.
I think maybe there is something wrong, but i haven't figure it out yet. 

but the metrics in your paper, acfnet, looks reasonable. 
Thanks a lot.

**Comment by youmi-zym** [comment]
Hi, @chenglong0313 
I think your result is reasonable, low EPE is quite easy for Noc area but difficult for Occ area. Especially when your model has converged.
Furthermore, the occlusion metric in my paper is based on SceneFlow, where occluded pixels account for only near 16%. 
However, the situation is quite different from KITTI due to its sparse disparity point.  We don't suggest doing occlusion evaluation on KITTI because may be numerous pixels cannot find the corresponding point in the target image.

**Comment by chenglong0313** [comment]
I see. Thanks a lot for your quick reply.
